name: expression-store
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::dask
  - conda-forge::click
  - conda-forge::progressbar
  - conda-forge::requests
  - bioconda::pyranges
