name: expression-store
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::dask
  - conda-forge::click
  - conda-forge::sqlalchemy
  - conda-forge::sqlalchemy-utils
  - conda-forge::psycopg2
  - conda-forge::pyodbc
  - conda-forge::pg8000
  - conda-forge::requests
  - bioconda::pyranges
